baseurl: '/pnd'
exclude: ['README.md']
permalink: pretty
title: 'Peoples Next Door'

google_analytics_id: ""
homepage:
  show_call_box: false
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: '© 2021. All rights reserved. This site may earn from qualifying purchases as an Amazon Associate.'

seo:
  meta_og_title: "Peoples Next Door"
  meta_og_type: "website"
  meta_og_url: "https://keelancook.ml/pnd"
  meta_og_image: "https://i.imgur.com/tXS9fHE.png"
  meta_og_description: "The Peoples Next Door website is an equipping hub for local churches seeking to engage the least-reached diaspora communities in their area."
  meta_twitter_card: "summary"
  meta_twitter_site: "@keelancook"
  meta_twitter_creator: "@keelancook"

collections:
  resources:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
